#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -f *.{eps,pdf}
rm -rf 0/
rm -rf constant/polyMesh
rm -f system/blockMeshDict constant/boundary

# ----------------------------------------------------------------- end-of-file
