#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

if [ ! -f constant/polyMesh/boundary ]
then
  (cd ../mesh
   ./Allrun $1
  )
fi

rm -rf 0
mkdir 0
cp org0/* 0

# Set boundary conditions
runApplication changeDictionary

# Set initial conditions
runApplication setDiscreteFields

if [ "x$1" = "x-parallel" ]
then
    runApplication decomposePar
    runParallel $application 4
    runApplication reconstructPar -latestTime
else
    runApplication $application
fi
