#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Sample
runApplication foamCalc mag U -latestTime
runApplication foamLog log.simpleFoam
runApplication sample -latestTime

# Postprocessing
nohup gnuplot res.gp
nohup gnuplot probes.gp
paste sets/*/measuringPoints_k_magU.xy exp/thermistor.txt > corvelocityThermistor.txt
nohup gnuplot corvelocityThermistor.gp >& /dev/null
nohup gnuplot velocityThermistor.gp >& /dev/null

epsfiles="res.eps probes.eps velocityThermistor.eps corvelocityThermistor.eps"

dir=`basename $PWD`
if [ "$dir" = "0deg" ];then
  paste sets/*/measuringPoints_k_magU.xy exp/split.txt > corvelocitySplit.txt
  nohup gnuplot velocitySplit.gp >& /dev/null
  nohup gnuplot corvelocitySplit.gp >& /dev/null
  epsfiles="$epsfiles velocitySplit.eps corvelocitySplit.eps"
fi

convert -density 300 -resize 2400x2400 $epsfiles plot.pdf

