#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

if [ ! -d constant/polyMesh ]
then
    cp -r ../mesh/constant/polyMesh constant/
fi

rm -rf 0
mkdir 0
cp org0/* 0

# Set boundary conditions
runApplication changeDictionary

# Set initial conditions
runApplication setDiscreteFields

# Run
if [ "x$1" = "x-parallel" ]
then
    runApplication decomposePar
    runParallel potentialFoam 4 -writep
    runParallel $application 4
    runApplication reconstructPar -latestTime
else
    runApplication potentialFoam -writep
    runApplication $application
fi

./Allplot
