#!/bin/sh
# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

model="${PWD##*/}"

if [ "x$model" != "xshare" ]
then
    rm -rf 0 > /dev/null 2>&1
    rm -f *.pdf *.eps *.txt > /dev/null 2>&1
fi

rm -rf constant/polyMesh 
cleanCase
