#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

share="../share"

# Check if sharable mesh  has already been created
if [ ! -f constant/polyMesh/points ]
then
    ( cd $share; ./Allrun.mesh )
fi

# Preprocessing
./Allrun.pre $*

# Residual monitor
./Allrun.monitor $* &

# Run
./Allrun.solve $*

# Postprocessing
./Allrun.post $*

# Plot
./Allrun.plot $*
