#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp constant/blockMeshDict constant/polyMesh/
runApplication blockMesh

runApplication snappyHexMesh -overwrite

rm -f constant/{cellLevel,pointLevel}

runApplication checkMesh -constant
runApplication renumberMesh -overwrite
