#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp constant/blockMeshDict constant/polyMesh/
runApplication blockMesh

if [ "x$1" = "x-parallel" ]
then
    runApplication decomposePar
    runParallel snappyHexMesh 4
    runApplication reconstructParMesh -latestTime
    rm -rf constant/polyMesh/*
    mv 1/polyMesh/* constant/polyMesh/
    rm -rf 1
else
    runApplication snappyHexMesh -overwrite
fi

rm -f constant/{cellLevel,pointLevel}

runApplication checkMesh -constant
runApplication renumberMesh -overwrite
