#!/bin/sh
#    This file is part of caseB.
#
#    caseB is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    caseB is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with caseB.  If not, see <http://www.gnu.org/licenses/>.

# Copyright (c) 2010-2017 Takuya OSHIMA <oshima@eng.niigata-u.ac.jp>.
# Copyright (c) 2014-2017 Masashi Imano <masashi.imano@gmail.com>.

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

model="${PWD##*/}"

if [ "x$model" = "xshare" ]
then
    cleanCase
    rm -rf 0 constant/polyMesh > /dev/null 2>&1
    rm -f system/blockMeshDict > /dev/null 2>&1
else
    cleanCase
    rm -rf *.eps *.pdf *.txt *.foam > /dev/null 2>&1
fi
