#!/bin/sh
#    This file is part of caseB.
#
#    caseB is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    caseB is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with caseB.  If not, see <http://www.gnu.org/licenses/>.

# Copyright (c) 2010-2014 Takuya OSHIMA <oshima@eng.niigata-u.ac.jp>.
# Copyright (c) 2014 Masashi Imano <masashi.imano@gmail.com>.

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`
model="${PWD##*/}"
share="../share"

if [ "x$model" = "xshare" ]
then
    # Create mesh
    runApplication ./makeMesh

    # Copy uninitialized fields to 0
    rm -rf 0 > /dev/null 2>&1
    cp -pr org0 0

    # Exit now if the script is run from the share directory
    exit 0
fi

# Create stab for the ParaView-reader
touch $model.foam

# Check if sharable resources has already been created
if [ ! -d 0 ]
then
    ( cd $share; ./Allrun )
fi

# Run
if [ "x$1" = "x-parallel" ]
then
    runApplication decomposePar
    runParallel $application $(getNumberOfProcessors)
    runApplication reconstructPar
else
    runApplication $application
fi

# Sample
runApplication sample -latestTime

# Postprocessing
runApplication python $share/postprocess.py $model
gnuplot <<EOF
    # Common settings
    set st d lp
    set size 1, 0.8
    set key box
    set grid
    set term post eps color "Helvetica" 21

    # Plot horizontal distribution of normalized velocity
    set xla \
        "Location (1-: Region 1, 14-: R. 2, 38-: R. 3, 11-: R. 4, 94-: R. 5)"
    set yla "Normalized velocity" offset 1
    set xtics ("1" 1, "14" 11, "38" 50, "11" 74, "94" 98, "115" 115)
    set out "horizontal_U_$model.eps"
    file = "horizontal_U_processed_$model.txt"
    plot [1:115] file u 1:3 lw 4 t "Wind tunnel", \
         file u 1:4 lw 4 t "OpenFOAM ($model)"

    # Plot vertical profile of normalized velocity
    set xla "x [m]"
    set yla "z [m]" offset 1
    set xtics (-0.075, 0, 0.1, 0.2, 0.3, 0.4)
    set ytics (0, 0.1, 0.2, 0.3, 0.35)
    set object 1 rect from -0.025,0 to 0.025, 0.2
    set out "verticalProfile_U_$model.eps"
    plot [-0.1:0.5] \
        "UMeasuredVertical_processed_$model.txt" lw 4 t "Wind tunnel", \
        "vertical_U_processed_$model.txt" w lp lw 4 t "OpenFOAM ($model)"

    # Plot vertical profile of k
    set out "verticalProfile_k_$model.eps"
    plot [-0.1:0.5] \
        "kMeasuredVertical_processed_$model.txt" lw 4 t "Wind tunnel", \
        "vertical_k_processed_$model.txt" w lp lw 4 t "OpenFOAM ($model)"
EOF
